FROM node:22.13.0-alpine

WORKDIR /app

COPY package*.json ./

RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    pkgconfig \
    pixman-dev \
    cairo-dev \
    pango-dev \
    libjpeg-turbo-dev \
    giflib-dev \
    libc6-compat \
    openssl

RUN npm install

COPY prisma ./prisma/

RUN npx prisma generate

COPY . .

EXPOSE 3000
ENV PORT=3000

CMD sh -c "npx prisma migrate dev && npm run dev"